# Generated by Django 3.2.6 on 2022-12-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_parent_task'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentslog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
