# Generated by Django 3.2.6 on 2022-12-26 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0006_historicalincident"),
        ("notes", "0002_commentslog_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentslog",
            name="incident",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="incidents.incident"
            ),
        ),
    ]
