# Generated by Django 3.2.16 on 2022-12-29 20:50

from typing import Any

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_commentslog_contact"),
        ("notes", "0003_commentslog_incident"),
    ]

    operations: list[Any] = []
