# Generated by Django 4.1.7 on 2023-05-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0060_remove_historicalvendorsurvey_can_anonymous_user_and_more"),
        ("notes", "0005_commentslog_risk"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentslog",
            name="survey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendor.vendorsurvey",
            ),
        ),
    ]
