# Generated by Django 3.2.6 on 2022-10-06 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from apps.tasks.models import TaskCreatedBy


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_add_contract_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.IntegerField(choices=TaskCreatedBy.choices, default=0, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
