# Generated by Django 3.2.6 on 2022-10-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_alter_risk_rating'),
        ('tasks', '0005_added_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risks.risk'),
        ),
    ]
