# Generated by Django 3.2.6 on 2022-10-21 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_status'),
        ('tasks', '0006_added_task_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.incident'),
        ),
    ]
