# Generated by Django 3.2.6 on 2022-10-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_added_task_incident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
    ]
