# Generated by Django 3.2.6 on 2022-11-02 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0019_alter_contact_role'),
        ('tasks', '0008_rename_name_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
