# Generated by Django 4.1.5 on 2023-01-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_historicaltask"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
