# Generated by Django 4.1.7 on 2023-05-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0024_unitdepartmentproces"),
        ("tasks", "0013_historicaltask_is_deleted_task_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="administrator.location",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrator.location",
            ),
        ),
    ]
