version: '3.8'

volumes:
  pgdata:


services:
  app:
    container_name: grc-app
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
    build: .

  redis:
    image: redis:alpine

  celery-worker:
    build: .
    command: celery -A core worker -l info
    environment:
      - CELERY_BROKER=redis://redis:6379
      - CELERY_BACKEND=redis://redis:6379
    depends_on:
      - app
      - redis

  celery-beat:
    build: .
    command: celery -A core beat -l info
    environment:
      - CELERY_BROKER=redis://redis:6379
      - CELERY_BACKEND=redis://redis:6379
    depends_on:
      - app
      - redis
      - celery-worker

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mvp
      - POSTGRES_PASSWORD=mvp
      - POSTGRES_DB=gracen-poc
