# Generated by Django 3.2.6 on 2022-10-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_alter_risk_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='name',
            new_name='title',
        ),
    ]
