# Generated by Django 3.2.6 on 2022-10-29 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_rename_name_risk_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='severity',
            new_name='impact',
        ),
    ]
