# Generated by Django 3.2.6 on 2022-10-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_rename_severity_risk_impact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='likelyhood',
            new_name='likelihood',
        ),
    ]
