# Generated by Django 4.1.5 on 2023-03-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "djf_surveys",
            "0013_orgsurvey_remove_question_org_remove_survey_org_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="orgquestion",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
