# Generated by Django 4.1.5 on 2023-03-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0016_organswer_document_alter_organswer_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgquestion",
            name="ordering",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Defines the question order within the surveys.",
                verbose_name="ordering",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="ordering",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Defines the question order within the surveys.",
                verbose_name="ordering",
            ),
        ),
    ]
