# Generated by Django 4.1.5 on 2023-03-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0017_alter_orgquestion_ordering_alter_question_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgquestion",
            name="help_text",
            field=models.CharField(
                blank=True,
                help_text="You can add a help text in here.",
                max_length=500,
                null=True,
                verbose_name="help text",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="help_text",
            field=models.CharField(
                blank=True,
                help_text="You can add a help text in here.",
                max_length=500,
                null=True,
                verbose_name="help text",
            ),
        ),
    ]
