# Generated by Django 4.1.5 on 2023-04-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0019_orgsurvey_gracen_survey_orgsurvey_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=1024, null=True)),
            ],
        )
    ]
