# Generated by Django 4.1.5 on 2023-04-04 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0020_questionheader_remove_orgquestion_header_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgquestion",
            name="header",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djf_surveys.questionheader",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="header",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djf_surveys.questionheader",
            ),
        ),
    ]
