# Generated by Django 4.1.5 on 2023-04-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0022_orgsurvey_status_survey_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgsurvey",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orgsurvey",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Not Sent"),
                    (2, "Sent"),
                    (3, "Viewed"),
                    (4, "In Progress"),
                    (5, "In Review"),
                    (6, "In Remediation"),
                    (7, "Completed"),
                    (8, "Cancelled"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Not Sent"),
                    (2, "Sent"),
                    (3, "Viewed"),
                    (4, "In Progress"),
                    (5, "In Review"),
                    (6, "In Remediation"),
                    (7, "Completed"),
                    (8, "Cancelled"),
                ],
                null=True,
            ),
        ),
    ]
