# Generated by Django 4.1.5 on 2023-04-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0023_orgsurvey_last_activity_survey_last_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organswer",
            name="na_explain",
            field=models.TextField(
                blank=True,
                help_text="NA explain of the answer given by the user.",
                max_length=500,
                null=True,
                verbose_name="na_explain",
            ),
        ),
        migrations.AlterField(
            model_name="orgquestion",
            name="type_field",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Text"),
                    (1, "Number"),
                    (2, "Radio"),
                    (3, "Select"),
                    (4, "Multi Select"),
                    (5, "Text Area"),
                    (6, "URL"),
                    (7, "Email"),
                    (8, "Date"),
                    (9, "Rating"),
                    (10, "Document"),
                    (11, "Yes-No-NA"),
                ],
                verbose_name="type of input field",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type_field",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Text"),
                    (1, "Number"),
                    (2, "Radio"),
                    (3, "Select"),
                    (4, "Multi Select"),
                    (5, "Text Area"),
                    (6, "URL"),
                    (7, "Email"),
                    (8, "Date"),
                    (9, "Rating"),
                    (10, "Document"),
                    (11, "Yes-No-NA"),
                ],
                verbose_name="type of input field",
            ),
        ),
    ]
