# Generated by Django 4.1.5 on 2023-04-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "djf_surveys",
            "0024_organswer_na_explain_alter_orgquestion_type_field_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="na_explain",
            field=models.TextField(
                blank=True,
                help_text="NA explain of the answer given by the user.",
                max_length=500,
                null=True,
                verbose_name="na_explain",
            ),
        ),
    ]
