# Generated by Django 4.1.5 on 2023-04-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djf_surveys", "0025_answer_na_explain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgsurvey",
            name="can_anonymous_user",
        ),
        migrations.RemoveField(
            model_name="orgsurvey",
            name="deletable",
        ),
        migrations.RemoveField(
            model_name="orgsurvey",
            name="duplicate_entry",
        ),
        migrations.RemoveField(
            model_name="orgsurvey",
            name="editable",
        ),
        migrations.RemoveField(
            model_name="orgsurvey",
            name="private_response",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="can_anonymous_user",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="deletable",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="duplicate_entry",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="editable",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="private_response",
        ),
    ]
