# Generated by Django 4.1.7 on 2023-05-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "organizations",
            "0004_organizationinvitation",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("equipment_type", models.CharField(max_length=1024)),
                ("asset_id", models.CharField(max_length=1024)),
                (
                    "serial_num",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("vendor", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "inservice_date",
                    models.DateField(blank=True, max_length=1024, null=True),
                ),
                (
                    "retired_date",
                    models.DateField(blank=True, max_length=1024, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
