# Generated by Django 4.1.7 on 2023-05-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0057_added_last_activity"),
        ("equipments", "0002_remove_equipment_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendor.vendor",
            ),
        ),
    ]
