# Generated by Django 4.1.7 on 2023-05-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0003_equipment_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="vendor",
        ),
    ]
