# Generated by Django 4.1.7 on 2023-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0004_remove_equipment_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="vendor",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
