# Generated by Django 4.1.7 on 2023-05-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0057_added_last_activity"),
        ("systems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="hosting",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Saas"),
                    (2, "Vendor Hosted"),
                    (3, "Cloud"),
                    (4, "Data Center"),
                    (5, "Onprem"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendor.vendor",
            ),
        ),
    ]
