# Generated by Django 4.1.7 on 2023-05-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0002_alter_system_hosting_alter_system_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="system",
            name="vendor",
        ),
    ]
