# Generated by Django 4.1.7 on 2023-05-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0003_remove_system_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="vendor",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
