# Generated by Django 3.2.6 on 2022-10-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_add_businessunit_department_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, choices=[('OFAC', 'OFAC'), ('OTHER', 'OTHER')], max_length=1000, null=True)),
                ('scheduled_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('WAITING', 'WAITING'), ('RUNNING', 'RUNNING'), ('ACTIVE', 'ACTIVE'), ('COMPLETED', 'COMPLETED'), ('ERROR_OCCURED', 'ERROR_OCCURED')], max_length=255, null=True)),
                ('run_instantly', models.BooleanField(default=False)),
                ('error_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OFACSpeciallyDesignatedNational',
            fields=[
                ('id', models.IntegerField(help_text='unique record identifier/unique listing identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='name of SDN', max_length=350, null=True)),
                ('sdn_type', models.CharField(blank=True, help_text='type of SDN', max_length=12, null=True)),
                ('program', models.CharField(blank=True, help_text='sanctions program name', max_length=200, null=True)),
                ('title', models.CharField(blank=True, help_text='title of an individual', max_length=200, null=True)),
                ('call_sign', models.CharField(blank=True, help_text='vessel call sign', max_length=8, null=True)),
                ('vess_type', models.CharField(blank=True, help_text='vessel type', max_length=25, null=True)),
                ('tonnage', models.CharField(blank=True, help_text='vessel tonnage', max_length=14, null=True)),
                ('grt', models.CharField(blank=True, help_text='gross registered tonnage', max_length=8, null=True)),
                ('vess_flag', models.CharField(blank=True, help_text='vessel flag', max_length=40, null=True)),
                ('vess_owner', models.CharField(blank=True, help_text='vessel owner', max_length=150, null=True)),
                ('remarks', models.TextField(blank=True, help_text='remarks on SDN', null=True)),
            ],
        ),
    ]
