# Generated by Django 3.2.6 on 2022-10-18 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0004_jobschedule_ofacspeciallydesignatednational'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEmailService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
