# Generated by Django 3.2.16 on 2022-10-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_add_testemailservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsetting',
            name='business_process_level',
            field=models.CharField(blank=True, choices=[('LEVEL_1', 'LEVEL_1'), ('LEVEL_2', 'LEVEL_2'), ('LEVEL_3', 'LEVEL_3')], max_length=255, null=True),
        ),
    ]
