# Generated by Django 3.2.6 on 2022-11-04 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("administrator", "0006_alter_organizationsetting_business_process_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobschedule",
            name="job_name",
            field=models.CharField(
                blank=True,
                choices=[("OFAC", "OFAC"), ("SENDGRID_EMAIL", "SENDGRID_EMAIL"), ("OTHER", "OTHER")],
                max_length=1000,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ScheduledJobLogger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("api_url", models.CharField(blank=True, max_length=1000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("response_code", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[("OFAC", "OFAC"), ("SENDGRID_EMAIL", "SENDGRID_EMAIL"), ("OTHER", "OTHER")],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
