# Generated by Django 3.2.6 on 2022-11-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0007_create_job_loggerer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledjoblogger",
            name="user",
        ),
        migrations.AddField(
            model_name="scheduledjoblogger",
            name="email",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
