# Generated by Django 3.2.6 on 2022-11-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_add_email_to_logger'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofacspeciallydesignatednational',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ofacspeciallydesignatednational',
            name='ent_num',
            field=models.IntegerField(blank=True, help_text='unique record identifier/unique listing identifier', null=True),
        ),
        migrations.AddField(
            model_name='ofacspeciallydesignatednational',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ofacspeciallydesignatednational',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='OFACSpeciallyDesignatedNationalAlternate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_num', models.IntegerField(help_text='unique record identifier')),
                ('alt_type', models.CharField(blank=True, help_text='type of alternate identity (aka, fka, nka)', max_length=8, null=True)),
                ('alt_name', models.CharField(blank=True, help_text='alternate identity name', max_length=350, null=True)),
                ('alt_remarks', models.CharField(blank=True, help_text='remarks on alternate identity', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sdn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.ofacspeciallydesignatednational')),
            ],
        ),
        migrations.CreateModel(
            name='OFACSpeciallyDesignatedNationalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_num', models.IntegerField(help_text='unique record identifier')),
                ('address', models.CharField(blank=True, help_text='street address of SDN', max_length=750, null=True)),
                ('address_line_2', models.CharField(blank=True, help_text='city, state/province, zip/postal code', max_length=116, null=True)),
                ('country', models.CharField(blank=True, help_text='country of address', max_length=250, null=True)),
                ('add_remarks', models.CharField(blank=True, help_text='remarks on address', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sdn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.ofacspeciallydesignatednational')),
            ],
        ),
    ]
