# Generated by Django 3.2.6 on 2022-11-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_remove_task_from_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSchedule',
        ),
    ]
