# Generated by Django 3.2.6 on 2022-11-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0020_contact_ignore_sdn'),
        ('administrator', '0012_delete_jobschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofacsdnresult',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.contact'),
        ),
    ]
