# Generated by Django 3.2.16 on 2022-11-20 01:01

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0014_testsdnservices"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestSDNServices",
        ),
        migrations.RemoveField(
            model_name="ofacspeciallydesignatednational",
            name="unique_identifier",
        ),
        migrations.AddField(
            model_name="ofacspeciallydesignatednationaladdress",
            name="ent_num",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ofacspeciallydesignatednationalalternate",
            name="ent_num",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ofacspeciallydesignatednational",
            name="created_at",
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AlterField(
            model_name="ofacspeciallydesignatednational",
            name="ent_num",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ofacspeciallydesignatednational",
            name="id",
            field=models.CharField(max_length=17, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ofacspeciallydesignatednationaladdress",
            name="add_num",
            field=models.IntegerField(help_text="unique record/listing identifier"),
        ),
        migrations.AlterField(
            model_name="ofacspeciallydesignatednationaladdress",
            name="created_at",
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AlterField(
            model_name="ofacspeciallydesignatednationaladdress",
            name="id",
            field=models.CharField(max_length=17, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ofacspeciallydesignatednationalalternate",
            name="alt_num",
            field=models.IntegerField(help_text="unique record/listing identifier"),
        ),
        migrations.AlterField(
            model_name="ofacspeciallydesignatednationalalternate",
            name="created_at",
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AlterField(
            model_name="ofacspeciallydesignatednationalalternate",
            name="id",
            field=models.CharField(max_length=17, primary_key=True, serialize=False),
        ),
    ]
