# Generated by Django 3.2.16 on 2022-11-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_ofac_model_admin_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofacsdnresult',
            options={'verbose_name': 'OFAC SDN Result', 'verbose_name_plural': 'OFAC SDN Results'},
        ),
    ]
