# Generated by Django 3.2.6 on 2022-11-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_organizationinvitation"),
        ("administrator", "0017_alter_ofacsdnresult_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"),
                ),
            ],
        ),
    ]
