# Generated by Django 4.1.5 on 2023-02-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0018_bulkimport"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
