# Generated by Django 4.1.7 on 2023-05-02 14:36

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0004_organizationinvitation",
        ),
        ("administrator", "0019_sitefeatures"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("line_1", models.CharField(blank=True, max_length=1024, null=True)),
                ("line_2", models.CharField(blank=True, max_length=1024, null=True)),
                ("city", models.CharField(blank=True, max_length=1024, null=True)),
                ("state", models.CharField(blank=True, max_length=2, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=9, null=True)),
                (
                    "location_type",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("location_code", models.CharField(max_length=1024)),
                ("landlord", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "primary_phone",
                    phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(default="2023-05-02", editable=False)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
