# Generated by Django 4.1.7 on 2023-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0020_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="updated_at",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
