# Generated by Django 4.1.7 on 2023-05-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0021_alter_location_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ofacsdnresult",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrator.location",
            ),
        ),
    ]
