# Generated by Django 4.1.7 on 2023-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0022_ofacsdnresult_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="ignore_sdn",
            field=models.BooleanField(default=False),
        ),
    ]
