# Generated by Django 4.1.5 on 2023-02-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_document_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="feature_permission",
            field=models.BooleanField(default=True),
        ),
    ]
