# Generated by Django 4.1.5 on 2023-04-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_feature_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_invited",
            field=models.BooleanField(default=False),
        ),
    ]
