# Generated by Django 4.1.7 on 2023-05-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_user_is_invited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="feature_permission",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
