# Generated by Django 3.2.6 on 2022-10-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.IntegerField(choices=[(1, 'Reported'), (2, 'Active'), (3, 'Extended Remediation'), (4, 'Closed'), (5, 'Non An Incident')], default=0),
        ),
    ]
