# Generated by Django 3.2.16 on 2022-10-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.IntegerField(choices=[(1, 'Reported'), (2, 'Active'), (3, 'Extended Remediation'), (4, 'Close'), (5, 'Not An Incident')], default=0),
        ),
    ]
