# Generated by Django 3.2.6 on 2022-10-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incident_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='name',
            new_name='title',
        ),
    ]
