# Generated by Django 3.2.6 on 2022-12-12 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0004_organizationinvitation"),
        ("incidents", "0005_alter_incident_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalIncident",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("title", models.CharField(max_length=1024)),
                ("description", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("root_cause", models.TextField(blank=True, null=True)),
                ("affected_resources", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "severity",
                    models.IntegerField(choices=[(1, "Low"), (2, "Medium"), (3, "High"), (4, "Critical")], default=0),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Reported"),
                            (2, "Active"),
                            (3, "Extended Remediation"),
                            (4, "Closed"),
                            (5, "Not An Incident"),
                        ],
                        default=0,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical incident",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
